[tool.poetry]
name = "sympyny"
version = "0.1.0"
description = ""
authors = ["Anonymous4045 <99518880+Anonymous4045@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
